$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    dots:false,
    autoplay:1000,
    responsive:{
        0:{
            items:1
        },
        768:{
            items:2
        }
    }
})